steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/api'
      - '-f'
      - 'api.Dockerfile'
      - '.'

  # 2. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/web'
      - '-f'
      - 'web.Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '.'

  # 3. Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/web']

  # 4. Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'local-aid-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/api'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'HOST=0.0.0.0,NODE_ENV=production,APP_KEY=${_APP_KEY},APP_NAME=${_APP_NAME},DRIVE_DISK=${_DRIVE_DISK},DB_CONNECTION=${_DB_CONNECTION},MYSQL_HOST=${_MYSQL_HOST},MYSQL_PORT=${_MYSQL_PORT},MYSQL_USER=${_MYSQL_USER},MYSQL_PASSWORD=${_MYSQL_PASSWORD},MYSQL_DB_NAME=${_MYSQL_DB_NAME},S3_KEY=${_S3_KEY},S3_SECRET=${_S3_SECRET},S3_BUCKET=${_S3_BUCKET},S3_REGION=${_S3_REGION},S3_ENDPOINT=${_S3_ENDPOINT},MAIL_HOST=${_MAIL_HOST},MAIL_PORT=${_MAIL_PORT},MAIL_USER=${_MAIL_USER},MAIL_PASSWORD=${_MAIL_PASSWORD},MAIL_FROM=${_MAIL_FROM},MAIL_SECURE=${_MAIL_SECURE},FRONTEND_URL=${_FRONTEND_URL}'
      - '--allow-unauthenticated'

  # 5. Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'local-aid-web'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/local-aid-repo/web'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _API_URL: 'https://api.localaid.site'
  _APP_KEY: 'DTJ0jvV5LWyqDoAoGsmdZziBISnNGDji'
  _APP_NAME: 'LocalAid'
  _DRIVE_DISK: 'local'
  _DB_CONNECTION: 'mysql'
  _MYSQL_HOST: '127.0.0.1' # UPDATE THIS to your production DB Host
  _MYSQL_PORT: '3306'
  _MYSQL_USER: 'u689750009_abeeranoor'
  _MYSQL_PASSWORD: '\$Ameer.com12'
  _MYSQL_DB_NAME: 'u689750009_infinia'
  _S3_KEY: 'dummyKey'
  _S3_SECRET: 'dummySecret'
  _S3_BUCKET: 'dummyBucket'
  _S3_REGION: 'dummyRegion'
  _S3_ENDPOINT: 'dummyEndpoint'

  _MAIL_HOST: 'smtp.hostinger.com'
  _MAIL_PORT: '465'
  _MAIL_USER: 'sohaib@zentacode.com'
  _MAIL_PASSWORD: '\$Ameer.com12'
  _MAIL_FROM: 'sohaib@zentacode.com'
  _MAIL_SECURE: 'true'
  _FRONTEND_URL: 'https://localaid.site'